# fly.toml app configuration file generated for wevs-hng1 on 2023-09-09T13:00:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wevs-hng1"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
